AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Mining Service\n"
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
    - local
    - dev
    - test
    - sit
    - preprod
    - prod
    Description: Environment
  Platform:
    Type: String
    Default: illuvium
    Description: platform information
  System:
    Type: String
    Default: mining
    Description: System information
  Subsystem:
    Type: String
    Default: webapi
    Description: Subsystem information
  Version:
    Type: String
    Default: 1.0.0
    Description: Version information
  Owner:
    Type: String
    Default: Ron Faur
    Description: Version information
  LambdaRoleArn:
    Type: String
    Default: arn:aws:iam::598396454095:role/mining-lambda-role
  TableName:
    Type: String
    Default: miningjobs
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '10'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '10'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
Globals:
  Function:
    Environment:
      Variables:
        Application__Version:
          Ref: Version
        Application__Environment:
          Ref: Environment
        Application__MachineName: Lambda
        Application__System:
          Ref: System
        Application__Subsystem:
          Ref: Subsystem
        Application__Platform:
          Ref: Platform
Resources:
  MiningTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dev-miningjobs
      AttributeDefinitions:
      - AttributeName: JobId
        AttributeType: S
      KeySchema:
      - AttributeName: JobId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST'"
      TracingEnabled: false
  PostEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role:
        Ref: LambdaRoleArn
      Runtime: dotnetcore3.1
      MemorySize: 1024
      Timeout: 10
      CodeUri: s3://mining-lambda-artifacts/c08376a0b5d0192334b30aee17ee1194
      Handler: MiningService.PostMine::MiningService.PostMine.Function::FunctionHandler
      FunctionName: miningservice-postmine
      Environment:
        Variables:
          Application__Name: miningservice-postmine
      Events:
        AddMining:
          Type: Api
          Properties:
            RestApiId:
              Ref: WebApi
            Path: /mine
            Method: POST
  GetEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role:
        Ref: LambdaRoleArn
      Runtime: dotnetcore3.1
      MemorySize: 1024
      Timeout: 20
      CodeUri: s3://mining-lambda-artifacts/d8aec9e018b52f78182ba1503775726f
      Handler: MiningService.GetMine::MiningService.GetMine.Function::FunctionHandler
      FunctionName: miningservice-getmine
      Environment:
        Variables:
          Application__Name: miningservice-getmine
      Events:
        GetIp:
          Type: Api
          Properties:
            RestApiId:
              Ref: WebApi
            Path: /mine
            Method: GET
Outputs:
  MiningTableOutput:
    Value:
      Fn::GetAtt:
      - MiningTable
      - Arn
    Description: Database ARN
